### ISSUE TITLE
Improve test suite speed

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer-rules#149]
Currently we have no concurency in test: https://github.com/Bearer/bearer-rules/blob/main/jest.config.js this is mostly an issue when running the test locally.

**Comment by cfabianski** [comment]
We would need to change the way we setup the file to the tmp folder since we keep overwriting the content at the moment.

**Comment by cfabianski** [comment]
See also https://github.com/Bearer/bearer/issues/1405 which might help
