### ISSUE TITLE
Go GA Language Rules

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer-rules#271]
Bringing the Go rules to GA will be a three-step process. 

1. Improve rule coverage

We currently have 44 Go rules as a static language we can probably look to Java as a source of inspiration

Focus - We have identified the following CWE as providing high value

- [x] CWE-502 https://github.com/Bearer/bearer-rules/pull/273
- [x] CWE-117 https://github.com/Bearer/bearer-rules/pull/275

Other CWE where we might be lacking and require some investigation:
- [x] CWE-78 https://github.com/Bearer/bearer-rules/pull/281 and https://github.com/Bearer/bearer-rules/pull/287
- [x] CWE-80 https://github.com/Bearer/bearer-rules/pull/283
- [x] ~CWE-185~ CWE-625 https://github.com/Bearer/bearer-rules/pull/288
- [ ] ~CWE-208~ 
- [x] CWE-295 https://github.com/Bearer/bearer-rules/pull/285 @cfabianski 
- [x] CWE-330 https://github.com/Bearer/bearer-rules/pull/284 @cfabianski 
- [x] CWE-259 https://github.com/Bearer/bearer-rules/pull/282 @cfabianski 
- [x] CWE-601 https://github.com/Bearer/bearer-rules/pull/279 @cfabianski 

2. Re-enable tests for HTML tag rule: https://github.com/Bearer/bearer-rules/issues/286

3. Add 3rd party API rules (CWE-201 - "Insertion of Sensitive Information Into Sent Data"). This is the list from other languages supported by bearer-rules, and part of this step will be to investigate which of these APIs are supported by Go:

- [x] Airbrake
- [x] Algolia
- [x] BigQuery 
- [x] Google Analytics
- [x] Bugsnag
- [x] Clickhouse
- [x] Datadog
- [x] Elasticsearch
- [x] New Relic
- [x] Open Telemetry
- [x] Rollbar
- [x] Segment 
- [x] Sentry
- [x] Honeybadger
- [ ] ~Scout APM~ (not available for Go)
- [x] Google Analytics
- [x] Google Dataflow

4. Battle test 💪 

- [x] False positive case in CWE-1004 cookie rule https://github.com/Bearer/bearer-rules/issues/351

**Comment by elsapet** [comment]
@didroe @gotbadger I've raised https://github.com/Bearer/bearer-rules/issues/351 (it came up during battle-testing). I've added it to the "Battle test" section here since we probably want to look at as part of GA

**Comment by elsapet** [comment]
Closing as completed by https://github.com/Bearer/bearer-rules/releases/tag/v0.34.0
