### ISSUE TITLE
Split rules that have OPTIONAL_DATA_TYPE

### ISSUE THREAD

**Issue by elsapet** [Bearer/bearer-rules#292]
As we move to static severity, we should split out rules with patterns that catch on "optional data type". These should be separated into a rule with data type patterns, with a higher severity, and a rule without data type patterns, with a lower severity. 

The following rules are candidates for this change:  

- [ ] go/lang/weak_hash_md5.yml
- [ ] go/lang/weak_hash_sha1.yml
- [ ] javascript/lang/weak_encryption_des.yml
- [ ] javascript/lang/weak_encryption_rc4.yml
- [ ] javascript/lang/weak_hash_md5.yml
- [ ] javascript/lang/weak_hash_sha1.yml
- [ ] python/lang/weak_hash_md5.yml
- [ ] python/lang/weak_hash_sha1.yml
- [ ] python/lang/weak_password_encryption_md5.yml
- [ ] python/lang/weak_password_encryption_sha1.yml
- [ ] ruby/lang/http_insecure.yml
- [ ] ruby/lang/insecure_ftp.yml
- [ ] ruby/lang/http_get_params.yml
- [ ] ruby/lang/weak_encryption_blowfish.yml
- [ ] ruby/lang/weak_encryption_dsa.yml
- [ ] ruby/lang/weak_encryption_rc4.yml
- [ ] ruby/lang/weak_encryption_rsa.yml
- [ ] ruby/lang/weak_hash_dss.yml
- [ ] ruby/lang/weak_hash_md.yml
- [ ] ruby/lang/weak_hash_sha.yml

**Comment by gotbadger** [comment]
no longer relevant after the sev review
