### ISSUE TITLE
Add hardcoded password rule for python support

### ISSUE THREAD

**Issue by aryanxk02** [Bearer/bearer-rules#325]
## Description
As part of our ongoing efforts to enhance security measures, how about we add a new rule for detecting hardcoded passwords in Python.

## Objective:
The objective of this rule is to identify instances where passwords are directly embedded within Python code.

## Proposed Rule Details:
```
Rule ID: python_lang_hardcoded_passwords
Description: Detects hardcoded passwords within Python code.
Detection Pattern:
pattern: |
    $<NAME> = $<STRING_LITERAL>.encode()
```

**Comment by gotbadger** [comment]
Python is currently in Alpha so there are not many rules. This particually rule will be undertaken as part of the work to get Python to a Beta level #171 Python Beta work will likely be undertakin in the next few months at the moment our foucs is on the Java & Go GA.

FYI we dont really take contributions for none GA languages as a lot of thought and testing goes into making the core language rules and often the engine itself may need to tweaks to support a full set of rules.
