### ISSUE TITLE
Ruby: Unexpected behaviour for ruby_rails_render_using_user_input

### ISSUE THREAD

**Issue by jbockler** [Bearer/bearer-rules#357]
Since the latest change to the rule (#356) bearer finds an issue in our code and i don't get why.
Can someone explain to me if this is intentional or a bug?

## Description & Reproduction

We have a controller action were the user can download some data:

```ruby
    content = FooModel.export_data(current_user, from, to, params[:search])
    send_data(content, type: "text/plain", disposition: "attachment; filename=raw_export.txt")
```

```bash
 bearer scan . --only-rule=ruby_rails_render_using_user_input
 ````
## Expected Behavior

The code should be fine as the params are not given into a raw HTML string.

## Actual Behavior

```
HIGH: Unsanitized user input in raw HTML strings (XSS) [CWE-79]
https://docs.bearer.com/reference/rules/ruby_rails_render_using_user_input

File: app/controllers/foo_controller.rb:24

 24     send_data(content, type: "text/plain", disposition: "attachment; filename=raw_export.txt")
=====================================

1 checks, 1 findings

CRITICAL: 0
HIGH: 1 (CWE-79)
MEDIUM: 0
LOW: 0
WARNING: 0
```

I have narrowed it down to the params that are the problem here, but this error is also triggered with permitted parameters.

## Your Environment

- Operating System and version: macOS 14.4.1 (23E224)
- Output of 'bearer version':
```
bearer version 1.43.1, build e267aa91d68a9e3e70890b03ded971b12c30d95f
```

**Comment by didroe** [comment]
Sorry, this is a bug. We should only be triggering for `send_data` when the disposition is `inline`. We will release a new version shortly

**Comment by jbockler** [comment]
All right, thanks for the quick response @didroe 👍
