### ISSUE TITLE
Update YAML keys for description and remediation_message

### ISSUE THREAD

**Issue by elsapet** [Bearer/bearer-rules#8]
Something for discussion: 

Following https://github.com/Bearer/bearer/pull/844 perhaps it is clearer to rename these attributes to avoid confusion. 
Note: depending on the implementation, this is potentially a breaking change for user's custom rules and will impact the documentation generation too.

`description` to be renamed `title`
`remediation_message` to be renamed `description`

Alternatively, we avoid the possible confusion by reworking the changes in https://github.com/Bearer/bearer/pull/844 so that `description` and `remediation_message` appear in the output.

**Comment by gotbadger** [comment]
Think this is probably more trouble than its worth for now so closing.
